site_name: Guia de Dados e IA - UFSCar
theme: 
  name: material
  features:
    - navigation.tabs

nav: 
- Início: index.md
- Sobre o Curso: sobre-o-curso.md
- Matérias:
  - 1º Semestre: 
    - Visão Geral: materias/semestre-1/index.md
    - Fundamentos em Ciência de Dados e Inteligência Artificial: materias/semestre-1/fundamentos-ciencia-de-dados-e-ia.md
    - Exploração de Dados: materias/semestre-1/exploracao-de-dados.md
    - Cálculo I: materias/semestre-1/calculo-1.md
    - Teoria das probabilidades: materias/semestre-1/teoria-das-probabilidades.md
    - Introdução à Programação: materias/semestre-1/introducao-a-programacao.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

extra:
  generator: false