site_name: Guia de Dados e IA - UFSCar
theme: 
  name: material
  features:
    - navigation.tabs

nav: 
- Início: index.md
- Sobre o Curso: about.md
- Matérias:
  - 1º Semestre: 
    - Visão Geral: materias/semestre_1/index.md
    - Fundamentos em Ciência de Dados e Inteligência Artificial: materias/semestre_1/fundamentos_ciencia_de_dados_e_ia.md


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list

extra:
  generator: false